server:
  # 端口
  port: 8082
spring:
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: utf-8
    # 授权码（在邮箱开通服务时获取）
    password: KQHERGYKHDYJLILQ
#    password: EMGHKQXXBDVZZYVT
    # 发送者邮箱地址
    username: 18219027758@163.com
    # 端口（不同邮箱端口号不同）
    port: 25

  # rabbitmq配置
  rabbitmq:
    # 用户名
    username: root
    # 密码
    password: root
    # 服务器地址
    host: localhost
    # 端口
    port: 15672
    virtual-host: /
    listener:
      simple:
        #开启手动确认
        acknowledge-mode: manual